language: php

php:
  - '7.1'

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

before_install:
  - nvm install 8

install:
  - composer update --prefer-dist --no-interaction --prefer-stable --no-suggest
  - npm update

script:
  - npm run prod
  - php apprentice build
  - vendor/bin/phpunit

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: .build
  target-branch: gh-pages
  github-token: $GITHUB_TOKEN
  on:
    branch: master
